name: Build checkchan

on:
  workflow_dispatch:
  #repository_dispatch:

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Installation
      run: |
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
    - name: Docker buildx
      run: |
        echo $PASSWORD | sudo docker login -u $USERNAME --password-stdin
        sudo docker run --privileged --rm tonistiigi/binfmt --install all
        sudo docker buildx create --use --name mybuild
        sudo docker buildx inspect mybuild --bootstrap
    - name: Clone 
      run: |
        git clone https://github.com/easychen/checkchan-dist.git
        sed -i '1,4c FROM --platform=$TARGETPLATFORM alpine' checkchan-dist/docker/Dockerfile
        sed -i 's/RUN apk add --no-cache chromium/RUN apk add --no-cache chromium npm/g' checkchan-dist/docker/Dockerfile
    - name: Build && Push
      run: |
        cd checkchan-dist/docker
        sudo docker buildx build -t $USERNAME/checkchan --platform=linux/arm64,linux/amd64 --push .
