name: Build checkchan
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Installation depends
      run: |
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
    - name: Clone 
      run: |
        git clone https://hub.fastgit.xyz/easychen/checkchan-dist.git
        cd checkchan-dist/docker
        sed -i '1,4c FROM --platform=$TARGETPLATFORM alpine' Dockerfile
        sed -i 's/RUN apk add --no-cache chromium/RUN apk add --no-cache chromium npm/g' Dockerfile
    - name: Docker 
      run: |
        echo ${{ secrets.PASSWORD }} | sudo docker login -u "${{ secrets.USERNAME }}" --password-stdin
        sudo docker run --privileged --rm tonistiigi/binfmt --install all
        sudo docker buildx create --use --name mybuild
        sudo docker buildx inspect mybuild --bootstrap
    - name: Build && push
      run: |
        docker buildx build -t enticeu/checkchan --platform=linux/arm64,linux/amd64 --push .
