name: Docker Image CI

on:
  workflow_dispatch:

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:

  build:

    runs-on: ubuntu-laster

    steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
        
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${USERNAME}
          password: ${PASSWORD}
      
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
        
#       - name: Docker Buildx 
#         run: |
#           docker buildx create --use --name mybuild
#           docker buildx inspect mybuild --bootstrap

      - name: Clone 
        run: |
          git clone https://github.com/easychen/checkchan-dist.git
          sed -i 's/FROM/FROM --platform=$TARGETPLATFORM' checkchan-dist/docker/Dockerfile

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./checkchan-dist/docker/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${USERNAME}/checkchan:(date +%F)
          
          
